# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ai-assisted-coding',
                'doc_host': 'https://isabelarvelo.github.io',
                'git_url': 'https://github.com/isabelarvelo/ai-assisted-coding',
                'lib_path': 'ai_assisted_coding'},
  'syms': {'ai_assisted_coding.core': {'ai_assisted_coding.core.foo': ('core.html#foo', 'ai_assisted_coding/core.py')}}}
